---
- name: install epel and remi repository
  yum:
    name:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    disable_gpg_check: yes

- name: change amzn2-core priority from 10 to 99
  command: sed -i -e s/priority=10/priority=99/ /etc/yum.repos.d/amzn2-core.repo

- name: install php
  yum: 
    name: "{{item}}" 
    state: present
    enablerepo: remi-php74
  with_items:
    - php
    - php-cli
    - php-devel
    - php-common
    - php-json
    - php-xml
    - php-mbstring
    - php-pdo
    - php-gd
    - php-process
    - php-intl
    - php-mysql

- name: change amzn2-core priority from 99 to 10
  command: sed -i -e s/priority=99/priority=10/ /etc/yum.repos.d/amzn2-core.repo

- name: copy php.ini
  copy:
    src: ../templates/php.ini
    dest: /etc